on: [push]

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    name: Build container with Docker
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build docker image and run a smoke test
      id: build_docker_image
      run: |
        DOCKER_BUILDKIT=1 docker build -f Dockerfile -t ghcr.io/${{ github.repository_owner }}/warp_oidc:latest .
        docker run -d -p 5000:5000 --name warp_oidc ghcr.io/${{ github.repository_owner }}/warp_oidc:latest
        sleep 10

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

    - name: Push Docker Image
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/warp_oidc:latest
